### PR TITLE
updated code base to work with php 5 and above

### PR DESCRIPTION
**Pull request by stevleibelt**
Things I have done:
* increased minimal php version to 5.3
* updated require_once commands
* replaced "var" with either public or protected visibility (protected when variable starts with "_")
* prefixed functions with either public or protected (if method name starts with _ it will be protected). 
* updated composer.json
* removed pass by reference for objects since this is normal in php 5.3

### CODE REVIEW

**Comment by stevleibelt** [comment]
@algorhythm 

I am sorry for that. But neither [pear/pear](https://packagist.org/packages/pear/pear) nor [pear/ole](https://packagist.org/packages/pear/ole) are providing any kind of version or tag I could use.
I wanted to use the benefit from composer so I added the "pear/pear" package to it since it is used inside the code.

If there is a better option, I am happy to read from.

**Comment by algorhythm** [comment]
I'm not sure if I understand you exactly. What you did was setting the "minimum-stability" to "dev". And when I now runs composer in production with the option '--no-dev' the pear/Spreadsheet_Excel_Writer will not be installed. It is necessary to make a tag for each stable version. If you had a tag then I were able to switch back to the running version before.

**Comment by stevleibelt** [comment]
@algorhythm 

yes, I am on your side. I would also prefer having tags (for this repository, as well as for the two mentioned above).
But I am not the maintainer of this, nor the other projects, so I am not able to create tags (as far as I know).

@c-schmitz 

Are there any planes to introduce tags in the github repositories?

**Comment by Dezinger** [comment]
Why you accept this request without testing? It total crashed library!

**Comment by stevleibelt** [comment]
@Dezinger if it is a "total crashed library", it is my fault, not the one of @c-schmitz.
It is pretty hard to test this library full without any unit test.

Since we are all doing this in our free times, I will do my best do fix this issue as soon as possible. Feel free to prepare your own pull request in between.

**Comment by stevleibelt** [comment]
```php
Error: Cannot access protected property Spreadsheet_Excel_Writer_Parser::$_BIFF_version
```

Is the error I get after I wrote a unit test for it. @Dezinger is this the same on your side?

**Comment by stevleibelt** [comment]
@Dezinger 

I created a new [pull request](https://github.com/pear/Spreadsheet_Excel_Writer/pull/6). Feel free to give it a try with my [repository](https://github.com/stevleibelt/Spreadsheet_Excel_Writer/).

**Comment by stevleibelt** [comment]
@Dezinger 

did you have some time to test my fixed version?

**Pull request merged**
